# This file is overwritten by one in alphagov-deployment at deploy time
development:
  host: <%= ENV['MONGOID_HOST'] ||= "localhost" %>
  database: govuk_content_development
  persist_in_safe_mode: true
  use_activesupport_time_zone: true

test:
  host: <%= ENV['MONGOID_HOST'] ||= "localhost" %>
  # Don't want this interfering with a concurrent Publisher test run
  database: govuk_content_panopticon_test
  use_activesupport_time_zone: true

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGODB_URI'] %>
  use_activesupport_time_zone: true
